# Generated by Django 3.0.7 on 2020-07-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribe',
            new_name='email_subscribe',
        ),
    ]
