# Generated by Django 3.0.7 on 2020-07-13 11:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20200713_1556'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transaction',
            new_name='transaction_table',
        ),
    ]
