# Generated by Django 3.0.7 on 2020-07-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200713_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_table',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
